INSERT INTO "Food" (id, name, category, "caloriesPer100g", "proteinPer100g", "carbsPer100g", "fatPer100g", "defaultQty", "quantityMode", "gramsPerPiece", "isIndian")
VALUES
-- ==================== DALS & LEGUMES (raw) ====================
('masoor-whole-raw', 'Whole Masoor Dal (Raw)', 'Dal & Legumes', 343, 25, 60, 1, 50, 'grams', NULL, true),
('chana-dal-raw', 'Chana Dal (Raw)', 'Dal & Legumes', 357, 21, 60, 5, 50, 'grams', NULL, true),
('moong-whole-raw', 'Whole Moong Dal (Raw)', 'Dal & Legumes', 334, 24, 60, 1.3, 50, 'grams', NULL, true),
('moong-split-raw', 'Split Moong Dal (Raw)', 'Dal & Legumes', 348, 24, 60, 1.2, 50, 'grams', NULL, true),
('toor-dal-raw', 'Toor Dal / Arhar (Raw)', 'Dal & Legumes', 335, 22, 58, 1.7, 50, 'grams', NULL, true),
('urad-whole-raw', 'Whole Urad Dal (Raw)', 'Dal & Legumes', 341, 24, 59, 1.4, 50, 'grams', NULL, true),
('urad-split-raw', 'Split Urad Dal (Raw)', 'Dal & Legumes', 347, 25, 59, 1.5, 50, 'grams', NULL, true),
('moth-beans-raw', 'Moth Beans (Raw)', 'Dal & Legumes', 343, 23, 62, 1.6, 50, 'grams', NULL, true),
('horse-gram-raw', 'Horse Gram / Kulthi (Raw)', 'Dal & Legumes', 321, 22, 57, 0.6, 50, 'grams', NULL, true),
('kala-chana-raw', 'Black Chickpea / Kala Chana (Raw)', 'Dal & Legumes', 360, 19, 61, 6, 50, 'grams', NULL, true),
('kabuli-chana-raw', 'White Chickpea / Kabuli (Raw)', 'Dal & Legumes', 360, 19, 60, 6, 50, 'grams', NULL, true),
('lobia-raw', 'Black-Eyed Peas / Lobia (Raw)', 'Dal & Legumes', 336, 24, 60, 1.3, 50, 'grams', NULL, true),
('green-peas-dry', 'Dried Green Peas (Raw)', 'Dal & Legumes', 341, 24, 60, 1, 50, 'grams', NULL, true),
('rajma-raw', 'Kidney Beans / Rajma (Raw)', 'Dal & Legumes', 337, 24, 60, 1.1, 50, 'grams', NULL, true),
('soybean-raw', 'Soybean (Raw)', 'Dal & Legumes', 432, 36, 30, 20, 30, 'grams', NULL, true),
('green-gram-sprouts', 'Green Gram Sprouts (Raw)', 'Dal & Legumes', 38, 3.2, 7, 0.2, 100, 'grams', NULL, true),

-- ==================== FLOURS & GRAINS ====================
('wheat-flour-atta', 'Whole Wheat Flour / Atta', 'Rice & Grains', 340, 12, 70, 1.7, 50, 'grams', NULL, true),
('wheat-flour-maida', 'Refined Flour / Maida', 'Rice & Grains', 364, 10, 74, 1.5, 50, 'grams', NULL, true),
('bengal-gram-flour', 'Gram Flour / Besan', 'Rice & Grains', 387, 22, 57, 5.6, 50, 'grams', NULL, true),
('bajra-flour', 'Pearl Millet Flour / Bajra', 'Rice & Grains', 361, 11, 67, 5, 50, 'grams', NULL, true),
('jowar-flour', 'Sorghum Flour / Jowar', 'Rice & Grains', 349, 10, 72, 2, 50, 'grams', NULL, true),
('ragi-flour', 'Finger Millet Flour / Ragi', 'Rice & Grains', 328, 7, 72, 1.3, 50, 'grams', NULL, true),
('makki-flour', 'Corn Flour / Makki Atta', 'Rice & Grains', 355, 8, 77, 3.5, 50, 'grams', NULL, true),
('rice-flour', 'Rice Flour', 'Rice & Grains', 366, 6, 80, 1, 50, 'grams', NULL, true),
('semolina-sooji', 'Semolina / Sooji (Dry)', 'Rice & Grains', 360, 13, 73, 1, 50, 'grams', NULL, true),
('sago-sabudana', 'Sago / Sabudana', 'Rice & Grains', 351, 0.2, 87, 0.1, 50, 'grams', NULL, true),
('poha-dry', 'Poha / Flattened Rice (Dry)', 'Rice & Grains', 353, 7, 78, 1, 50, 'grams', NULL, true),
('vermicelli-dry', 'Vermicelli / Seviyan (Dry)', 'Rice & Grains', 352, 8, 78, 1.2, 50, 'grams', NULL, true),
('basmati-rice-raw', 'Basmati Rice (Raw)', 'Rice & Grains', 350, 7, 79, 0.5, 50, 'grams', NULL, true),
('brown-rice-raw', 'Brown Rice (Raw)', 'Rice & Grains', 370, 7.5, 77, 2.7, 50, 'grams', NULL, true),
('quinoa-raw', 'Quinoa (Raw)', 'Rice & Grains', 368, 14, 64, 6, 50, 'grams', NULL, true),
('amaranth-ramdana', 'Amaranth / Ramdana', 'Rice & Grains', 371, 14, 65, 7, 30, 'grams', NULL, true),
('barley-raw', 'Barley / Jau (Raw)', 'Rice & Grains', 354, 12, 73, 2.3, 50, 'grams', NULL, true),

-- ==================== EGGS & DAIRY ====================
('egg-yolk-raw', 'Egg Yolk (Raw)', 'Eggs & Dairy', 322, 16, 3.6, 27, 1, 'piece', 18, true),
('buffalo-milk', 'Buffalo Milk', 'Eggs & Dairy', 97, 3.7, 5.2, 6.9, 250, 'ml', NULL, true),
('skim-milk', 'Skim Milk (0.1% fat)', 'Eggs & Dairy', 34, 3.4, 5, 0.1, 250, 'ml', NULL, true),
('soy-milk', 'Soy Milk', 'Eggs & Dairy', 44, 3.3, 3.3, 2, 250, 'ml', NULL, true),
('almond-milk', 'Almond Milk', 'Eggs & Dairy', 29, 0.4, 3, 1.4, 250, 'ml', NULL, false),
('cream-fresh', 'Fresh Cream / Malai', 'Eggs & Dairy', 292, 2.5, 3, 30, 30, 'grams', NULL, true),
('cream-heavy', 'Heavy Cream (35% fat)', 'Eggs & Dairy', 340, 2, 2.8, 37, 30, 'grams', NULL, false),
('sour-cream', 'Sour Cream', 'Eggs & Dairy', 198, 2.4, 4.6, 19, 30, 'grams', NULL, false),
('khoa-mawa', 'Khoa / Mawa (Milk Solids)', 'Eggs & Dairy', 421, 16, 26, 31, 50, 'grams', NULL, true),
('mozzarella', 'Mozzarella Cheese', 'Eggs & Dairy', 280, 22, 3, 20, 50, 'grams', NULL, false),
('cheddar-cheese', 'Cheddar Cheese', 'Eggs & Dairy', 403, 25, 1.3, 33, 30, 'grams', NULL, false),
('processed-cheese', 'Processed Cheese Slice', 'Eggs & Dairy', 290, 18, 4, 23, 1, 'piece', 20, false),
('cream-cheese', 'Cream Cheese', 'Eggs & Dairy', 342, 6, 4, 34, 30, 'grams', NULL, false),

-- ==================== MEAT (raw) ====================
('chicken-breast-raw', 'Chicken Breast (Raw)', 'Chicken & Meat', 120, 23, 0, 2.6, 200, 'grams', NULL, true),
('chicken-wing-raw', 'Chicken Wing (Raw)', 'Chicken & Meat', 203, 18, 0, 14, 150, 'grams', NULL, true),
('chicken-mince-raw', 'Chicken Mince / Keema (Raw)', 'Chicken & Meat', 143, 20, 0, 7, 200, 'grams', NULL, true),
('mutton-leg-raw', 'Mutton Leg (Raw)', 'Chicken & Meat', 175, 19, 0, 11, 200, 'grams', NULL, true),
('mutton-mince-raw', 'Mutton Mince / Keema (Raw)', 'Chicken & Meat', 210, 16, 0, 16, 200, 'grams', NULL, true),
('lamb-chops', 'Lamb Chops (Raw)', 'Chicken & Meat', 230, 20, 0, 17, 2, 'piece', 75, true),
('goat-meat-raw', 'Goat Meat / Bakra (Raw)', 'Chicken & Meat', 130, 21, 0, 5, 200, 'grams', NULL, true),
('pork-raw', 'Pork (Raw Lean)', 'Chicken & Meat', 242, 21, 0, 18, 150, 'grams', NULL, false),
('bacon-raw', 'Bacon (Raw)', 'Chicken & Meat', 541, 12, 1.4, 54, 50, 'grams', NULL, false),
('duck-meat-raw', 'Duck Meat (Raw)', 'Chicken & Meat', 337, 11, 0, 31, 150, 'grams', NULL, false),
('turkey-breast-raw', 'Turkey Breast (Raw)', 'Chicken & Meat', 114, 24, 0, 1.4, 200, 'grams', NULL, false),

-- ==================== BREADS (more) ====================
('rumali-roti', 'Rumali Roti', 'Bread & Roti', 280, 9, 55, 4, 1, 'piece', 50, true),
('tandoori-roti', 'Tandoori Roti', 'Bread & Roti', 285, 10, 55, 4, 1, 'piece', 60, true),
('bhatura', 'Bhatura (Fried Bread)', 'Bread & Roti', 310, 7, 42, 13, 1, 'piece', 80, true),
('lachha-paratha', 'Lachha Paratha (Layered)', 'Bread & Roti', 320, 8, 45, 13, 1, 'piece', 80, true),
('kerala-parotta', 'Kerala Parotta', 'Bread & Roti', 340, 7, 44, 16, 1, 'piece', 90, true),
('sheermal', 'Sheermal (Saffron Bread)', 'Bread & Roti', 310, 8, 50, 9, 1, 'piece', 60, true),
('bakarkhani', 'Bakarkhani', 'Bread & Roti', 320, 7, 52, 10, 1, 'piece', 50, true),

-- ==================== REGIONAL DISHES ====================
('shorshe-ilish', 'Shorshe Ilish (Mustard Hilsa)', 'Indian Dishes', 185, 16, 3, 12, 150, 'grams', NULL, true),
('kosha-mangsho', 'Kosha Mangsho (Bengali Mutton)', 'Indian Dishes', 210, 18, 4, 14, 200, 'grams', NULL, true),
('chingri-malai', 'Chingri Malai Curry (Prawn)', 'Indian Dishes', 175, 15, 4, 11, 200, 'grams', NULL, true),
('macher-jhol', 'Macher Jhol (Bengali Fish Curry)', 'Indian Dishes', 120, 16, 4, 5, 200, 'grams', NULL, true),
('dhokar-dalna', 'Dhokar Dalna (Bengali Lentil Cake Curry)', 'Indian Dishes', 130, 6, 12, 7, 200, 'grams', NULL, true),
('bisi-bele-bath', 'Bisi Bele Bath (Karnataka)', 'Indian Dishes', 135, 5, 22, 3.5, 300, 'grams', NULL, true),
('sambar-rice', 'Sambar Rice', 'Indian Dishes', 125, 5, 22, 3, 300, 'grams', NULL, true),
('avial', 'Avial (Mixed Veg Coconut Curry)', 'Indian Dishes', 95, 3, 10, 5, 200, 'grams', NULL, true),
('kadhi-pakora', 'Kadhi Pakora (Gram Flour Yogurt Curry)', 'Indian Dishes', 115, 5, 12, 6, 250, 'grams', NULL, true),
('bharwa-bhindi', 'Bharwa Bhindi (Stuffed Okra)', 'Indian Dishes', 95, 3, 9, 5.5, 150, 'grams', NULL, true),
('gatte-ki-sabzi', 'Gatte ki Sabzi (Rajasthani)', 'Indian Dishes', 160, 8, 18, 7, 200, 'grams', NULL, true),
('ker-sangri', 'Ker Sangri (Rajasthani Desert Beans)', 'Indian Dishes', 110, 5, 15, 4, 150, 'grams', NULL, true),
('dal-bati-churma', 'Dal Bati Churma', 'Indian Dishes', 280, 12, 42, 8, 1, 'piece', 150, true),
('vindaloo-chicken', 'Chicken Vindaloo (Goan)', 'Indian Dishes', 165, 18, 6, 8, 200, 'grams', NULL, true),
('goan-fish-curry', 'Goan Fish Curry', 'Indian Dishes', 140, 16, 5, 7, 200, 'grams', NULL, true),
('bebinca', 'Bebinca (Goan Layered Dessert)', 'Sweets & Desserts', 380, 5, 45, 20, 1, 'piece', 80, true),
('hyderabadi-biryani', 'Hyderabadi Chicken Biryani', 'Indian Dishes', 190, 12, 24, 6, 300, 'grams', NULL, true),
('mirchi-ka-salan', 'Mirchi ka Salan (Hyderabadi)', 'Indian Dishes', 95, 2, 8, 6, 150, 'grams', NULL, true),
('bagara-baingan', 'Bagara Baingan (Hyderabadi Eggplant)', 'Indian Dishes', 110, 3, 9, 7, 200, 'grams', NULL, true),
('sarson-da-saag', 'Sarson da Saag (Punjabi)', 'Indian Dishes', 65, 3, 9, 2.5, 200, 'grams', NULL, true),
('chole-bhature-dish', 'Chole Bhature (Full Plate)', 'Indian Dishes', 350, 12, 48, 14, 1, 'serving', 300, true),
('pani-puri-plate', 'Pani Puri (6 pcs plate)', 'Snacks & Street Food', 180, 4, 28, 6, 6, 'piece', 18, true),

-- ==================== MORE SWEETS ====================
('shrikhand', 'Shrikhand', 'Sweets & Desserts', 280, 6, 35, 13, 100, 'grams', NULL, true),
('basundi', 'Basundi (Thickened Milk)', 'Sweets & Desserts', 260, 8, 30, 12, 150, 'grams', NULL, true),
('rabdi', 'Rabdi / Rabri', 'Sweets & Desserts', 290, 6, 28, 17, 100, 'grams', NULL, true),
('gaajar-halwa', 'Gaajar Halwa (Carrot)', 'Sweets & Desserts', 270, 5, 32, 14, 150, 'grams', NULL, true),
('moong-dal-halwa', 'Moong Dal Halwa', 'Sweets & Desserts', 350, 8, 42, 18, 150, 'grams', NULL, true),
('gajar-halwa', 'Gajar Halwa', 'Sweets & Desserts', 270, 4, 33, 14, 150, 'grams', NULL, true),
('doodh-peda', 'Doodh Peda', 'Sweets & Desserts', 390, 9, 45, 20, 1, 'piece', 30, true),
('balushahi', 'Balushahi', 'Sweets & Desserts', 420, 5, 48, 24, 1, 'piece', 40, true),
('ghevar', 'Ghevar (Rajasthani)', 'Sweets & Desserts', 410, 4, 42, 26, 1, 'piece', 60, true),
('kalakand', 'Kalakand', 'Sweets & Desserts', 340, 12, 40, 16, 1, 'piece', 50, true),
('rasmalai', 'Rasmalai', 'Sweets & Desserts', 210, 8, 24, 10, 1, 'piece', 60, true),
('modak', 'Modak (Ukadiche)', 'Sweets & Desserts', 220, 4, 40, 6, 2, 'piece', 50, true),
('pathishapta', 'Pathishapta (Bengali Crepe)', 'Sweets & Desserts', 260, 6, 35, 11, 2, 'piece', 50, true),
('payasam', 'Payasam (South Indian Kheer)', 'Sweets & Desserts', 150, 4, 25, 4, 200, 'grams', NULL, true),
('seviyan-kheer', 'Seviyan Kheer', 'Sweets & Desserts', 160, 4, 28, 4.5, 150, 'grams', NULL, true),

-- ==================== FASTING / VRAT FOODS ====================
('sabudana-khichdi', 'Sabudana Khichdi', 'Indian Dishes', 180, 2.5, 38, 3, 200, 'grams', NULL, true),
('kuttu-puri', 'Kuttu Puri (Buckwheat)', 'Bread & Roti', 280, 6, 38, 12, 2, 'piece', 30, true),
('samak-rice', 'Samak Rice / Barnyard Millet', 'Rice & Grains', 150, 3, 30, 1.5, 200, 'grams', NULL, true),
('singhara-halwa', 'Singhara Halwa (Water Chestnut)', 'Sweets & Desserts', 220, 3, 40, 6, 100, 'grams', NULL, true),
('rajgira-ladoo', 'Rajgira Ladoo (Amaranth)', 'Sweets & Desserts', 350, 8, 50, 14, 1, 'piece', 30, true),

-- ==================== SOUPS ====================
('tomato-soup', 'Tomato Soup', 'Indian Dishes', 55, 1.5, 8, 2, 250, 'ml', NULL, true),
('mulligatawny', 'Mulligatawny Soup', 'Indian Dishes', 90, 4, 10, 4, 250, 'ml', NULL, true),
('sweet-corn-soup', 'Sweet Corn Soup', 'Indian Dishes', 75, 3, 12, 2, 250, 'ml', NULL, true),
('hot-sour-soup-chicken', 'Chicken Hot & Sour Soup', 'Indian Dishes', 65, 5, 6, 2, 250, 'ml', NULL, true),
('spinach-soup', 'Spinach Soup', 'Indian Dishes', 45, 2.5, 5, 1.5, 250, 'ml', NULL, true),

-- ==================== FATS / OILS / SPREADS ====================
('mustard-oil', 'Mustard Oil', 'Healthy & Fitness', 900, 0, 0, 100, 10, 'ml', NULL, true),
('groundnut-oil', 'Groundnut / Peanut Oil', 'Healthy & Fitness', 900, 0, 0, 100, 10, 'ml', NULL, true),
('sunflower-oil', 'Sunflower Oil', 'Healthy & Fitness', 884, 0, 0, 100, 10, 'ml', NULL, true),
('rice-bran-oil', 'Rice Bran Oil', 'Healthy & Fitness', 884, 0, 0, 100, 10, 'ml', NULL, true),
('sesame-oil', 'Sesame Oil / Til Oil', 'Healthy & Fitness', 900, 0, 0, 100, 10, 'ml', NULL, true),
('vanaspati', 'Vanaspati / Dalda', 'Healthy & Fitness', 900, 0, 0, 100, 10, 'grams', NULL, true),
('desi-ghee', 'Desi Ghee (Cow)', 'Eggs & Dairy', 900, 0, 0, 100, 10, 'grams', NULL, true),
('margarine', 'Margarine', 'Healthy & Fitness', 717, 0.9, 0.7, 81, 10, 'grams', NULL, false),
('mayonnaise', 'Mayonnaise', 'Junk Food', 680, 1, 2, 75, 15, 'grams', NULL, false),

-- ==================== BAKERY ITEMS ====================
('biscuit-digestive', 'Digestive Biscuit', 'Junk Food', 480, 7, 62, 22, 2, 'piece', 15, false),
('biscuit-marie', 'Marie Biscuit', 'Junk Food', 430, 7, 70, 12, 3, 'piece', 10, false),
('biscuit-cream', 'Cream Biscuit', 'Junk Food', 500, 6, 64, 24, 2, 'piece', 15, false),
('biscuit-glucose', 'Glucose Biscuit / Parle G', 'Junk Food', 450, 8, 68, 14, 3, 'piece', 10, true),
('brown-bread', 'Brown Bread (Slice)', 'Bread & Roti', 243, 10, 44, 3.5, 2, 'piece', 25, true),
('pav', 'Pav (Dinner Roll)', 'Bread & Roti', 265, 8, 50, 4, 1, 'piece', 50, true),
('croissant', 'Croissant', 'Junk Food', 406, 8, 46, 21, 1, 'piece', 60, false),
('muffin-chocolate', 'Chocolate Muffin', 'Junk Food', 370, 5, 48, 18, 1, 'piece', 80, false),
('rusk', 'Rusk / Toast', 'Bread & Roti', 410, 10, 72, 9, 2, 'piece', 15, true),
('khari', 'Khari / Puff Biscuit', 'Junk Food', 500, 5, 50, 30, 2, 'piece', 15, true),

-- ==================== MORE BEVERAGES ====================
('cold-coffee', 'Cold Coffee (with Ice Cream)', 'Beverages', 110, 3, 14, 5, 300, 'ml', NULL, true),
('badaam-milk', 'Badaam Milk / Almond Milk Shake', 'Beverages', 120, 4, 16, 5, 250, 'ml', NULL, true),
('thandai', 'Thandai', 'Beverages', 130, 4, 18, 5, 250, 'ml', NULL, true),
('jaljeera', 'Jaljeera', 'Beverages', 15, 0.3, 3, 0.1, 250, 'ml', NULL, true),
('aam-panna', 'Aam Panna (Raw Mango Drink)', 'Beverages', 45, 0.5, 11, 0.2, 250, 'ml', NULL, true),
('rooh-afza', 'Rooh Afza (Rose Syrup Drink)', 'Beverages', 60, 0, 15, 0, 250, 'ml', NULL, true),

-- ==================== CONDIMENTS ====================
('soy-sauce', 'Soy Sauce', 'Chinese', 53, 8, 8, 0.1, 10, 'ml', NULL, false),
('vinegar', 'Vinegar', 'Chinese', 21, 0, 1, 0, 10, 'ml', NULL, false),
('chilli-sauce', 'Chilli Sauce', 'Chinese', 120, 1.5, 24, 0.4, 15, 'grams', NULL, false),
('tomato-ketchup', 'Tomato Ketchup', 'Junk Food', 101, 1, 25, 0.1, 15, 'grams', NULL, false),
('peanut-chutney', 'Peanut Chutney', 'Indian Dishes', 260, 10, 10, 20, 30, 'grams', NULL, true),
('tamarind-dates-chutney', 'Tamarind Date Chutney', 'Indian Dishes', 160, 1, 38, 0.5, 30, 'grams', NULL, true),

-- ==================== PANEER (more) ====================
('paneer-bhurji', 'Paneer Bhurji (Scrambled)', 'Indian Dishes', 175, 11, 5, 12, 150, 'grams', NULL, true),
('mutter-paneer', 'Mutter Paneer', 'Indian Dishes', 180, 8, 8, 13, 200, 'grams', NULL, true),
('paneer-do-pyaza', 'Paneer Do Pyaza', 'Indian Dishes', 185, 8, 7, 14, 200, 'grams', NULL, true),

-- ==================== CHICKEN (more) ====================
('lemon-chicken', 'Lemon Chicken', 'Indian Dishes', 140, 20, 5, 5, 200, 'grams', NULL, true),
('pepper-chicken', 'Pepper Chicken', 'Indian Dishes', 155, 22, 4, 6, 200, 'grams', NULL, true),
('chicken-korma', 'Chicken Korma', 'Indian Dishes', 195, 14, 6, 13, 200, 'grams', NULL, true)

ON CONFLICT (id) DO NOTHING;
